#!/usr/bin/env python3
"""Microsoft Graph API Bulk SharePoint / OneDrive Uploader for Migrated NotebookLM (.docx) Sources.

Reads `sharepoint_spmt_manifest.csv` generated by `gws_to_ge_notebooklm_migrator.py`
and uploads each user's staged `.docx` and `Notebook_Sources_Index.md` files
directly into SharePoint Online or OneDrive for Business via Microsoft Graph REST API v1.0.
"""

import argparse
import csv
import os
from pathlib import Path
from urllib.parse import quote
import requests


def upload_file_to_graph(
    access_token: str, drive_id: str, remote_folder_path: str, local_file: Path
) -> bool:
  rel_path = f"{remote_folder_path.strip('/')}/{local_file.name}"
  encoded_path = quote(rel_path)
  url = f"https://graph.microsoft.com/v1.0/drives/{drive_id}/root:/{encoded_path}:/content"
  headers = {
      "Authorization": f"Bearer {access_token}",
      "Content-Type": (
          "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      ),
  }
  resp = requests.put(
      url, headers=headers, data=local_file.read_bytes(), timeout=60
  )
  return resp.status_code in (200, 201)


def main():
  parser = argparse.ArgumentParser(
      description=(
          "Upload staged SharePoint .docx files via Microsoft Graph API v1.0"
      )
  )
  parser.add_argument(
      "--manifest-csv",
      required=True,
      help="Path to sharepoint_spmt_manifest.csv",
  )
  parser.add_argument(
      "--drive-id",
      required=True,
      help="Target SharePoint Document Library or OneDrive Drive ID",
  )
  parser.add_argument(
      "--graph-token",
      default=os.environ.get("MS_GRAPH_TOKEN", ""),
      help="Microsoft Graph Bearer token (Files.ReadWrite.All)",
  )
  args = parser.parse_args()

  if not args.graph_token:
    raise SystemExit(
        "Error: Provide --graph-token or set MS_GRAPH_TOKEN environment"
        " variable."
    )

  with open(args.manifest_csv, "r", encoding="utf-8") as cf:
    for row in csv.DictReader(cf):
      src_dir = Path(row["SourcePath"])
      sub_folder = (
          f"{row['M365_SharePoint_UPN']}/{row['TargetSubFolder']}".strip("/")
      )
      if not src_dir.exists():
        continue
      for root, _, files in os.walk(src_dir):
        for fname in sorted(files):
          fpath = Path(root) / fname
          rel_sub = Path(root).relative_to(src_dir).as_posix()
          remote_dir = (
              f"{sub_folder}/{rel_sub}" if rel_sub != "." else sub_folder
          )
          ok = upload_file_to_graph(
              args.graph_token, args.drive_id, remote_dir, fpath
          )
          print(f"[{'OK' if ok else 'FAIL'}] {fpath.name} -> {remote_dir}/")


if __name__ == "__main__":
  main()
